# Generated by Django 5.2 on 2025-05-08 07:44

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default="2000-01-01", validators=[users.models.validate_age]
            ),
            preserve_default=False,
        ),
    ]
