# Generated by Django 5.2 on 2025-05-08 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_contributor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contributor",
        ),
    ]
