# Generated by Django 5.2 on 2025-05-08 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributors", "0002_alter_contributor_unique_together_and_more"),
        ("projects", "0003_delete_contributor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                related_name="projects_contributed",
                through="contributors.Contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
