# Generated by Django 5.2 on 2025-05-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributors", "0001_initial"),
        ("projects", "0003_delete_contributor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_contributors",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
